# 예제2: 날씨 예보 프로그램
print('날씨 정보를 입력하세요')
date = input('날짜를 입력하세요 (XX월 XX일)')
day = input('요일을 입력하세요')
minTemp = int(input('아침 최저 기온을 입력하세요'))
maxTemp = int(input('낮 최고 기온을 입력하세요'))
rainprop = int(input('비올 확률을 입력하세요'))
microDust = input('미세먼지 수치를 입력하세요')
sunrise = input('일출시간을 입력하세요')
sunset = input('일몰시간을 입력하세요')
southWave = float(input('남해바다 물결 높이를 입력하세요'))
eastWave = float(input('동해바다 물결 높이를 입력하세요'))
westWave = float(input('서해바다 물결 높이를 입력하세요'))

print('-------------------------------------------------')
print('내일 날씨 예보입니다.')
print(day + '요일인 ' + date + '의 아침 최저 기온은 ' + str(minTemp) + '도, 낮 최고 기온은 ' + str(maxTemp) + '도로 예보됐습니다.')
print('비올 확률은 ' + str(rainprop) + '%이고, 미세먼지는 ' + microDust + ' 수준일 것으로 예상됩니다')
print('일출시간은 ' + sunrise + '이고, 일몰시간은 ' + sunset + '입니다')
print('바다의 물결은 남해 앞바다' + str(southWave) + 'm, 동해 앞바다' + str(eastWave) + 'm, 서해 앞바다' + str(westWave) + 'm 높이로 일겠습니다 ')
print('지금까지' + date + ' ' + day + '요일 날씨 예보였습니다')

print('-------------------------------------------------')
print('내일 날씨 예보입니다.')
print('{0}요일인 {1}의 아침 최저 기온은 {2}도, 낮 최고 기온은 {3}도로 예보됐습니다.'.format(day, date, minTemp, maxTemp))
print('비올 확률은 {0}%이고, 미세먼지는 {1}수준일 것으로 예상됩니다'.format(rainprop, microDust))
print('일출시간은 {0}이고, 일몰시간은 {1}입니다'.format(sunrise, sunset))
print('바다의 물결은 남해 앞바다 {0}m, 동해 앞바다 {1}m, 서해 앞바다 {2}m 높이로 일겠습니다'.format(southWave, eastWave, westWave))
print('지금까지 {0} {1}요일 날씨 예보였습니다'.format(date, day))

print('-------------------------------------------------')
print('내일 날씨 예보입니다.')
print('%s요일인 %s의 아침 최저 기온은 %d도, 낮 최고 기온은 %d도로 예보됐습니다.' % (day, date, minTemp, maxTemp))
print('비올 확률은 %d 이고, 미세먼지는 %s 수준일 것으로 예상됩니다' % (rainprop, microDust))
print('일출시간은 %s이고, 일몰시간은 %s입니다' % (sunrise, sunset))
print('바다의 물결은 남해 앞바다 %.1fm, 동해 앞바다 %.1fm, 서해 앞바다 %.1fm 높이로 일겠습니다' % (southWave, eastWave, westWave))
print('지금까지 %s %s요일 날씨 예보였습니다' % (date, day))
